name: "deploy"

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Set Yarn Version
        run: yarn set version 4.5.1

      - name: Setup Astro
        uses: withastro/action@v2
        with:
          node-version: "20.15.0"

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4

  tag:
    name: Tag
    needs: deploy
    runs-on: ubuntu-latest
    outputs:
      TAG_NAME: ${{ steps.tag.outputs.TAG_NAME }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Tag
        id: tag
        run: |
          TAG_NAME=$(TZ=Asia/Tokyo date +"%Y%m%d-%H%M%S")
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag $TAG_NAME
          git push origin $TAG_NAME
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_OUTPUT

  note:
    name: Note
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - name: Publish Release Note
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.tag.outputs.TAG_NAME }}
          generateReleaseNotes: true
